name: LLM Code Review

on:
  pull_request:
    paths:
      - "**.java"
      - "**.js"
      - "**.ts"
      - "**.cs"
      - "**.vb"
      - "**.py"
      - "**.jsx"
      - "**.tsx"
      - "**.json"
      - "**.html"
      - "**.css"
      - "**.md"
      - "**.yml"
      - "**.yaml"
      - "**.cjs"
      - "**.mjs"
      - "**.config.*"

jobs:
  llm-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # Add any required dependencies for LLM API here

      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v44
        with:
          separator: '\n'

      - name: Run LLM review
        env:
          LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
        run: |
          python .github/scripts/llm_review.py --provider "$LLM_PROVIDER" --api-key "$LLM_API_KEY" --files ${{ steps.files.outputs.all_changed_files }}
